# If you are not using Yandex Metrika, please change 'yandex-ID' to an empty string
yandex-ID: '65211277'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-M97J7ZHNF5'